/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CommandRequest } from "./CommandRequest";
import { CommandRequestCountArgs } from "./CommandRequestCountArgs";
import { CommandRequestFindManyArgs } from "./CommandRequestFindManyArgs";
import { CommandRequestFindUniqueArgs } from "./CommandRequestFindUniqueArgs";
import { DeleteCommandRequestArgs } from "./DeleteCommandRequestArgs";
import { CommandRequestService } from "../commandRequest.service";
@graphql.Resolver(() => CommandRequest)
export class CommandRequestResolverBase {
  constructor(protected readonly service: CommandRequestService) {}

  async _commandRequestsMeta(
    @graphql.Args() args: CommandRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CommandRequest])
  async commandRequests(
    @graphql.Args() args: CommandRequestFindManyArgs
  ): Promise<CommandRequest[]> {
    return this.service.commandRequests(args);
  }

  @graphql.Query(() => CommandRequest, { nullable: true })
  async commandRequest(
    @graphql.Args() args: CommandRequestFindUniqueArgs
  ): Promise<CommandRequest | null> {
    const result = await this.service.commandRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CommandRequest)
  async deleteCommandRequest(
    @graphql.Args() args: DeleteCommandRequestArgs
  ): Promise<CommandRequest | null> {
    try {
      return await this.service.deleteCommandRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
